context:
  version: "05.01.05"
  tag: ${{ version | replace(".", "-") }}

package:
  name: millepede
  version: ${{ version }}

source:
  url: https://gitlab.desy.de/millepede/millepede-ii/-/archive/V${{ tag }}/millepede-ii-V${{ tag }}.tar.gz
  sha256: c567c8f486194c1edf9e04c53c15f22635120be13e1de19c428f2eb088ae3222

build:
  script:
    - cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DBUILD_TESTS=ON ${CMAKE_ARGS}
    - cmake -LH build
    - cmake --build build --parallel ${CPU_COUNT}
    - cmake --install build
    - ctest --test-dir build -V
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("fortran") }}
    - ${{ stdlib("c") }}
    - cmake
    - ninja
  host:
    - zlib
    - numpy

tests:
  - package_contents:
      bin:
        - pede
        - convertMilleFormats
        - inspectMilleBinary
        - testMilleC
      lib:
        - Mille2
        - MilleC
      include:
        - Mille/IMilleReader.h
        - Mille/MilleDataStructures.h
        - Mille/MilleDecoder.h
        - Mille/MilleFactory.h
        - Mille/MilleReaderC.h
        - Mille/MilleReaderCSV.h
        - Mille/MilleReaderCcompressed.h
        - Mille/MilleRecord.h
        - Mille/MilleRecord.ixx
        - Mille/MilleRecordC.h
        - Mille/MilleRecordCSV.h
        - Mille/readMilleC.h
        - Mille/writeMilleC.h
      files:
        - cmake/*
        - modules/millef.mod
        - mp2setup.sh
        - python/*
      strict: true
  - script:
      - testMilleC

about:
  homepage: https://millepede.pages.desy.de/millepede-ii/index.html
  summary: 'Linear least squares solver for alignment and calibration of tracking detectors'
  description: |
    Millepede II is a package for linear least squares fits with a large number of parameters,
    developed for the alignment and calibration of tracking detectors.
  license: LGPL-2.0-or-later
  license_file: COPYING.LIB
  documentation: https://millepede.pages.desy.de/millepede-ii/draftman_page.html
  repository: https://gitlab.desy.de/millepede/millepede-ii

extra:
  recipe-maintainers:
    - utk4r-sh
    - GiacomoXT
    - vvsagar
    - AlexanderHeidelbach
